# Generated by Django 4.1.13 on 2025-04-25 08:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_reg_product_shop_produc_id_f21274_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reg',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='reg',
            name='shop_reg_usernam_d9673f_idx',
        ),
        migrations.AddField(
            model_name='reg',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reg',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reg',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reg',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reg',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
