# Generated by Django 4.1.13 on 2025-04-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_reg_managers_reg_first_name_reg_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone number'),
        ),
    ]
