# Generated by Django 5.2 on 2025-05-07 13:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_reg_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='phone',
        ),
        migrations.AddField(
            model_name='product',
            name='users_like',
            field=models.ManyToManyField(blank=True, related_name='products_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
